#include <uli.h>

// derived from keymap_it

static const uli_keycode TicKeyboardCodes[256] =
	{
uli_key_unknown,	 // KeyNone, 0x00
uli_key_unknown,	 // KeyNone, 0x01
uli_key_unknown,	 // KeyNone, 0x02
uli_key_unknown,	 // KeyNone, 0x03
uli_key_a,	 // 'a', 0x04
uli_key_b,	 // 'b', 0x05
uli_key_c,	 // 'c', 0x06
uli_key_d,	 // 'd', 0x07
uli_key_e,	 // 'e', 0x08
uli_key_f,	 // 'f', 0x09
uli_key_g,	 // 'g', 0x0A
uli_key_h,	 // 'h', 0x0B
uli_key_i,	 // 'i', 0x0C
uli_key_j,	 // 'j', 0x0D
uli_key_k,	 // 'k', 0x0E
uli_key_l,	 // 'l', 0x0F
uli_key_m,	 // 'm', 0x10
uli_key_n,	 // 'n', 0x11
uli_key_o,	 // 'o', 0x12
uli_key_p,	 // 'p', 0x13
uli_key_q,	 // 'q', 0x14
uli_key_r,	 // 'r', 0x15
uli_key_s,	 // 's', 0x16
uli_key_t,	 // 't', 0x17
uli_key_u,	 // 'u', 0x18
uli_key_v,	 // 'v', 0x19
uli_key_w,	 // 'w', 0x1A
uli_key_x,	 // 'x', 0x1B
uli_key_y,	 // 'y', 0x1C
uli_key_z,	 // 'z', 0x1D
uli_key_1,	 // '1', 0x1E
uli_key_2,	 // '2', 0x1F
uli_key_3,	 // '3', 0x20
uli_key_4,	 // '4', 0x21
uli_key_5,	 // '5', 0x22
uli_key_6,	 // '6', 0x23
uli_key_7,	 // '7', 0x24
uli_key_8,	 // '8', 0x25
uli_key_9,	 // '9', 0x26
uli_key_0,	 // '0', 0x27
uli_key_return,	 // KeyReturn, 0x28
uli_key_escape,	 // KeyEscape, 0x29
uli_key_backspace,	 // KeyBackspace, 0x2A
uli_key_tab,	 // KeyTabulator, 0x2B
uli_key_space,	 // KeySpace, 0x2C
uli_key_minus,	 // '-', 0x2D
uli_key_equals,	 // '=', 0x2E
uli_key_leftbracket,	 // '[', 0x2F
uli_key_rightbracket,	 // ']', 0x30
uli_key_backslash,	 // '\\', 0x31
uli_key_backslash,	 // '\\', 0x32
uli_key_semicolon,	 // ';', 0x33
uli_key_apostrophe,	 // '\'', 0x34
uli_key_grave,	 // '`', 0x35
uli_key_comma,	 // ',', 0x36
uli_key_period,	 // '.', 0x37
uli_key_slash,	 // '/', 0x38
uli_key_capslock,	 // KeyCapsLock, 0x39
uli_key_f1,		 // KeyF1, 0x3A
uli_key_f2,		 // KeyF2, 0x3B
uli_key_f3,		 // KeyF3, 0x3C
uli_key_f4,		 // KeyF4, 0x3D
uli_key_f5,		 // KeyF5, 0x3E
uli_key_f6,		 // KeyF6, 0x3F
uli_key_f7,		 // KeyF7, 0x40
uli_key_f8,		 // KeyF8, 0x41
uli_key_f9,		 // KeyF9, 0x42
uli_key_f10,		 // KeyF10, 0x43
uli_key_f11,		 // KeyF11, 0x44
uli_key_f12,		 // KeyF12, 0x45
uli_key_unknown,	 // KeyPrintScreen, 0x46
uli_key_unknown,	 // KeyScrollLock, 0x47
uli_key_unknown,	 // KeyPause, 0x48
uli_key_insert,		 // KeyInsert, 0x49
uli_key_home,		 // KeyHome, 0x4A
uli_key_pageup,		 // KeyPageUp, 0x4B
uli_key_delete,		 // KeyDelete, 0x4C
uli_key_end,		 // KeyEnd, 0x4D
uli_key_pagedown,	 // KeyPageDown, 0x4E
uli_key_right,		 // KeyRight, 0x4F
uli_key_left,		 // KeyLeft, 0x50
uli_key_down,		 // KeyDown, 0x51
uli_key_up,		 // KeyUp, 0x52
uli_key_unknown,	 // KeyNumLock, 0x53
uli_key_numpaddivide,	 // KeyKP_Divide, 0x54
uli_key_numpadmultiply,	 // KeyKP_Multiply, 0x55
uli_key_numpadminus,	 // KeyKP_Subtract, 0x56
uli_key_numpadplus,	 // KeyKP_Add, 0x57
uli_key_numpadenter,	 // KeyKP_Enter, 0x58
uli_key_numpad1,	 // KeyEnd, 0x59
uli_key_numpad2,	 // KeyDown, 0x5A
uli_key_numpad3,	 // KeyPageDown, 0x5B
uli_key_numpad4,	 // KeyLeft, 0x5C
uli_key_numpad5,	 // KeyKP_Center, 0x5D
uli_key_numpad6,	 // KeyRight, 0x5E
uli_key_numpad7,	 // KeyHome, 0x5F
uli_key_numpad8,	 // KeyUp, 0x60
uli_key_numpad9,	 // KeyPageUp, 0x61
uli_key_numpad0,	 // KeyInsert, 0x62
uli_key_numpadperiod,	 // KeyDelete, 0x63
uli_key_unknown,	 // '<', 0x64
uli_key_unknown,	 // KeyApplication, 0x65
uli_key_unknown,	 // KeyNone, 0x66
uli_key_unknown,	 // KeyNone, 0x67
uli_key_unknown,	 // KeyNone, 0x68
uli_key_unknown,	 // KeyNone, 0x69
uli_key_unknown,	 // KeyNone, 0x6A
uli_key_unknown,	 // KeyNone, 0x6B
uli_key_unknown,	 // KeyNone, 0x6C
uli_key_unknown,	 // KeyNone, 0x6D
uli_key_unknown,	 // KeyNone, 0x6E
uli_key_unknown,	 // KeyNone, 0x6F
uli_key_unknown,	 // KeyNone, 0x70
uli_key_unknown,	 // KeyNone, 0x71
uli_key_unknown,	 // KeyNone, 0x72
uli_key_unknown,	 // KeyNone, 0x73
uli_key_unknown,	 // KeyNone, 0x74
uli_key_unknown,	 // KeyNone, 0x75
uli_key_unknown,	 // KeyNone, 0x76
uli_key_unknown,	 // KeyNone, 0x77
uli_key_unknown,	 // KeyNone, 0x78
uli_key_unknown,	 // KeyNone, 0x79
uli_key_unknown,	 // KeyNone, 0x7A
uli_key_unknown,	 // KeyNone, 0x7B
uli_key_unknown,	 // KeyNone, 0x7C
uli_key_unknown,	 // KeyNone, 0x7D
uli_key_unknown,	 // KeyNone, 0x7E
uli_key_unknown // KeyNone, 0x7F

};
