@echo off

echo Processing .... luademo.uli ....
uli78_pro\bin\prj2cart demos\luademo.lua build\luademo.uli
echo Processing .... luademo.uli created ....
echo Processing .... luademo.uli.dat ....
uli78_pro\bin\bin2txt build\luademo.uli build\assets\luademo.uli.dat -z
echo Processing ....luademo.uli.dat created ....

echo Processing ..... cart.png.dat ...
uli78_pro\bin\bin2txt build\cart.png build\assets\cart.png.dat
echo Processing .....cart.png.dat created...

echo Processing localplayer-sdl.exe...
copy uli78_pro\bin\localplayer-sdl.exe uli78_pro\bin\localplayer.exe.dat > nul
copy uli78_pro\bin\SDL2.dll uli78_pro\bin\localplayer.exe.dll > nul
echo Processing ....localplayer.exe.dat created ...

echo Done.
