#!/bin/bash

FILES=`find ./demos -name uli78.zig`
for FILE in $FILES; do
  cp -v templates/zig/src/uli78.zig $FILE
done

FILES=`find ./demos -name build.zig`
for FILE in $FILES; do
  cp -v templates/zig/build.zig $FILE
done

